name: "Test"
on:
  pull_request:
  push:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = nix.sierrasoftworks.com:3T9XyoyEc7iw8BQNmXM2QPk2FQeW5Zo6KbLytdM+izY= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://nix.sierrasoftworks.com https://cache.nixos.org/
    - uses: cachix/cachix-action@v12
      with:
        name: sierrasoftworks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
    - run: nix-build release.nix
    - run: nix-shell --command 'echo "Build Completed"'

    - name: get secrets - nix-cache
      uses: hashicorp/vault-action@v2.4.2
      if: github.ref == 'refs/heads/main'
      with:
        url: https://vault.sierrasoftworks.com
        method: jwt
        path: github-actions
        role: build
        jwtGithubAudience: https://vault.sierrasoftworks.com
        secrets: |
          secrets/data/repos/SierraSoftworks/nixpkgs/signing-key private_key | NIX_SIGNING_KEY;
    - run: |
        nix --extra-experimental-features nix-command --extra-experimental-features flakes copy --to file:///tmp/cache $(type -p git-tool) $(type -p grey)
        
        # Signing of packages
        [[ -z "${NIX_SIGNING_KEY}" ]] && echo "No signing key imported, skipping signing" || { echo "${NIX_SIGNING_KEY}" > ./nix-cache-key.sec; }
        if [ -f ./nix-cache-key.sec ];
          nix --extra-experimental-features nix-command --extra-experimental-features flakes store sign -k ./nix-cache-key.sec --store file:///tmp/cache --all
          rm ./nix-cache-key.sec
        fi